### ISSUE TITLE
Desktop icon and previous repositories?

### ISSUE THREAD

**Issue by bshor** [glaure/tortoisehg4ubuntu#1]
Hello, this is the only set of instructions that allowed me to load tortoisehg on my Ubuntu 20.04 system! Thank you.

Two questions: 1) How do I save the icon somehow? When I load it from the command line, I see the icon, but I can't seem to save it as a favorite.

2) When I load from the command line, it defaults into the thg repository, which I don't care about. I want it to show me my repositories, but it seems to forget about them and I have to hunt them down in my file system. Is there something to do about that?

**Comment by glaure** [comment]
Hi,

I will have a look into your issues! (It will take a little time as I am quite occupied atm)

Gunther

**Comment by bshor** [comment]
Thank you!

**Comment by glaure** [comment]
Hi the latest 5.8.1 release seems to have these issues resolved.

**Comment by glaure** [comment]
Use 5.8.1
